### ISSUE TITLE
Bug:`CSSMediaRule` is not supported

### ISSUE THREAD

**Issue by stephanschubert** [csstools/css-has-pseudo#2]
First: Thank you for this nice PostCSS plugin!

Unfortunately there's no [`selectorText` property](https://github.com/csstools/css-has-pseudo/blob/master/src/browser.js#L103) on `CSSMediaRule` objects.

It contains an array of `cssRules` instead, e.g.:

```
n.cssText
> "@media (max-width: 48em) {
>   .hPECmK { font-size: 2rem; }
> }

n.cssRules[0].selectorText
> ".hPECmK"
```

**Comment by jonathantneal** [comment]
Thanks for reporting this. Would you please retest this in v0.6.0?

**Comment by stephanschubert** [comment]
It works now but I have opened another issue: https://github.com/csstools/css-has-pseudo/issues/3
