### ISSUE TITLE
Bug: Child selector `>` gets encoded

### ISSUE THREAD

**Issue by stephanschubert** [csstools/css-has-pseudo#4]
I tried to target a `figure` in a `div` via:

```css
div:has(> figure) { border: 1px solid red; }
```

The (broken) HTML looks like this:

```html
<div class="sc-bZQynM habWLe" :has(=""><figure>
```

I stepped into it with DevTools and saw:

```js
cssText: "div[\:has\(\%3e\%20figure\)] { border: 1px solid red; }"
```

[which happens here](https://github.com/csstools/css-has-pseudo/blob/master/src/postcss.js#L18) via `encodeURICompnent` I guess.

~Is this encoding necessary?~

EDIT: Scratch that; of course encoding `>` is necessary.. but somehow the HTML gets mangled though.

**Comment by jonathantneal** [comment]
At some point, I dropped an important `encodeURIComponent` function, probably when I reorganized where the encoding and decoding happen. It has been restored in 0.8.0, and this selector should now work.
