### ISSUE TITLE
How to install in a Nuxt project?

### ISSUE THREAD

**Issue by katerlouis** [csstools/css-has-pseudo#9]
I have no idea how to get this plugin up and running in a NuxtJS project.

When doing this in `nuxt.config.js`:
```js
build: {
  postcss: {
    plugins: {
      'css-has-pseudo': {},
    },
  },
},
```

I get the following error:
![image](https://user-images.githubusercontent.com/1983382/107548815-64e40700-6bcf-11eb-9c8a-c3bebfd486e0.png)

**Comment by romainmenke** [comment]
Hi @katerlouis we are archiving this repo as this plugin has moved to [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/tree/main/plugins/css-has-pseudo)

I am not personally familiar with NuxtJS but we have enabled [discussions in @csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/discussions/categories/q-a) which would be a great place to re-submit this question.
